### ISSUE TITLE
Configuring Stale with Github Labels with Emoji

### ISSUE THREAD

**Issue by bmuenzenmeyer** [probot/stale#104]
Could you provide an example of how to configure `stale.yml` with Github's new [emoji in labels](https://blog.github.com/2018-02-22-label-improvements-emoji-descriptions-and-more/)?

```
exemptLabels:
  - pinned ⚓️
```

or

```
exemptLabels:
  - pinned :anchor:
```

Thanks!!!

**Comment by LeoNatan** [comment]
It's already supported as can be seen here:
https://github.com/wix/detox/blob/master/.github/stale.yml

Use `""` when using an emoji.

**Comment by bmuenzenmeyer** [comment]
Thanks!
