### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by bkeepers** [probot/stale#11]
After deploying [throttling](https://github.com/probot/probot/pull/109), this is no longer hitting [abuse rate limits](https://developer.github.com/v3/#abuse-rate-limits), but now it's hitting the normal API [rate limits](https://developer.github.com/v3/#rate-limiting).

```
[error] { [Error: {"message":"API rate limit exceeded for installation:17424.","documentation_url":"https://developer.github.com/v3/#rate-limiting"}]
```

Currently the plugin runs a check against all repositories once/hour, which requires getting a list of all installations and all repositories and checking each repo for a config. An organization with a lot of repositories will quickly hit the rate limits.

Here are some ideas to make this more efficient and should avoid rate limit issues:

- [ ] on start, get all installations and repositories and set a random interval for checking each repository only if it has a `.github/stale.yml`
  - [ ] listen for a `push` event with a `.github/stale.yml` to enable the interval when a config is added
- [ ] Cache `.config/stale.yml`
- [ ] Increase interval from 1 hour

**Comment by bkeepers** [comment]
FYI @rafaelfranca, if it seems like the bot is not picking up everything, this is why.

**Comment by hzoo** [comment]
Increasing the interval to even 1 day would be fine, I don't think the granularity for this needs to be within 1 hour

**Comment by bkeepers** [comment]
Since #14 (which also visits repos on a random delay), it hasn't been getting any rate limit errors. I'm going to call this good enough for now, but if it crops up again, I think @hzoo's suggestion of backing off the interval is a good resolution.
