### ISSUE TITLE
Collect/publish anonymous stats about plugin usage

### ISSUE THREAD

**Issue by patcon** [probot/stale#113]
Curious to know:
1. Who is using this plugin?
1. How many maintainers?
1. How many contributors?
1. How many stars?
1. How many open issues/PRs?

Understanding the average project (and how that average and cohorts evolve over time) feels like it would be really useful in understanding what the proper defaults should be :)

**Comment by patcon** [comment]
Related: https://github.com/probot/metrics

Should these be made public so the community can understand what it's building together?

**Comment by bkeepers** [comment]
https://probot.github.io/apps/stale/ actually lists some of the largest organizations that are using it. You can also get a list of all the issues that the app has commented on [via GitHub search](https://github.com/search?q=commenter%3Aapp%2Fstale&ref=opensearch).

You're welcome to use that data to do any analysis.

**Comment by patcon** [comment]
While I still think it would be nice if there was interest in socializing curiosity around usage data as part of the project itself, I'm happy to do it elsewhere. Thanks for the tip, and I'll dig in when I have more time available :)

https://github.com/patcon/github-apps-stats-tools
