### ISSUE TITLE
Moving issue between project columns seems not considered as activity

### ISSUE THREAD

**Issue by pintergreg** [probot/stale#116]
I my repository Stale is set to 7 days, but issue was set to stale regardless column activity.

![kepernyokep_2018-04-17_08-16-41](https://user-images.githubusercontent.com/3854784/38851886-f1ae6b6a-4217-11e8-9fd4-013979f5e624.png)

**Comment by DanielMSchmidt** [comment]
I would like to introduce a new option that allows you to specify that tickets in a project cannot be stale. I plan my work ahead quite some time using projects and fighting against staleness there makes no sense to me.

I will try to look into it if I can propose a PR 😇

**Comment by DanielMSchmidt** [comment]
🙈 my work here is done *flies away*

No seriously, thank you for your help, I think I missed that option

**Comment by johlju** [comment]
Happy to help. Hope it works. I haven't tested that option myself yet.

**Comment by pintergreg** [comment]
Just to clarify things @johlju is right about  `exemptProjects`, but it was not the reason why I opened this issue. Practically all of my issues have to be in a project. In my workflow "being in a project" does not say anything about staleness, but sticking in the same column for a certain amount of time does.
On the other hand moving between columns is considered an activity and should "reset the timer".

**Comment by DanielMSchmidt** [comment]
Sorry @pintergreg I hijacked your issue thinking my topic would be near implementation wise :/ Next time I will open a new one and link it instead 🙈

**Comment by pintergreg** [comment]
@DanielMSchmidt No problem, I think that description is useful and actually I should have written it in the first place. :)

**Comment by hiimbex** [comment]
Stale also has an exempt labels section in the `.github/stale.yml` file:
```yml
# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - pinned
  - security
  - "[Status] Maybe Later"
```

You can customize these to an label you use on your issues/PRs. Hope this helps @pintergreg!

**Comment by pintergreg** [comment]
@hiimbex I am aware of `exemptLabels` and I use that option. With a lot of configuring and _extra manual work in the workflow_ it might be a workaround, but not what I would like to have.
