### ISSUE TITLE
Option to not count weekends

### ISSUE THREAD

**Issue by jsocol** [probot/stale#130]
We're looking at using Stalebot at work to help keep ourselves focused and limit the number of open PRs, which means having much shorter deadlines than most OSS projects (e.g. on the order of ~3 days). But that means that weekends can eat up a really significant portion of the time and we'd rather not count them.

I'm not sure exactly where the right spot to implement this would be—maybe the [`since`](https://github.com/probot/stale/blob/master/lib/stale.js#L198-L207) method could be weekend-aware?

For example if, if `daysUntilStale` is 3, and it's Monday, if the PR was touched on Friday, we'd want that to be OK, so we'd set `since` to return "last Wednesday" instead of "fast Friday".

Definitely think this should be an opt-in change, not the default behavior.

**Comment by bkeepers** [comment]
Hey @jsocol, thanks for the feedback. That's great that you have such quick turnarounds on your projects! You're welcome to fork this repo and try implementing it.

**Comment by jsocol** [comment]
Great! If the feature seems like something that'd be mergeable and that approach seems reasonable, we can take a crack at that.

**Comment by jsocol** [comment]
This can probably be closed for #138
