### ISSUE TITLE
Instantly close stale issues

### ISSUE THREAD

**Issue by kaelig** [probot/stale#131]
Thanks for the great bot!

How to instantly close a stale issue right after commenting/labelling?

**Comment by kaelig** [comment]
Thanks for the explanation. However, 0 is equivalent to "false" in YAML, maybe this is why it doesn't seem to work.

Mind reopening the issue?

**Comment by kaelig** [comment]
@bkeepers 🛎 friendly ping, as this is something I'd love to get to the bottom of!

**Comment by hiimbex** [comment]
I'm just popping in to give this a +1. I first saw this issue and changed my stale settings on my test org and totally forgot about this issue. But all my issues have been marked as stale, and none have been closed. I think the best solution @kaelig is to set `daysUntilClose: 1`. It still won't be automatic, but it will be sooner.

I do think this might be a worthwhile feature though @bkeepers.

**Comment by matthiasbeyer** [comment]
Hi. I am currently looking for a bot that can instantly close PRs and Issues (as in "as soon as they are opened). This issue seems somewhat related, so I'm asking here: Would it be possible to use the stale bot to close PRs instantly? (I'm more interested in PRs as github has a way to disable issues, but not PRs).

**Comment by kaelig** [comment]
I wonder if tagging the value as an integer would work (untested):

```yaml
daysUntilClose: !!int 0
```

**Comment by Dids** [comment]
Wouldn't something like `-1` work better though?

**Comment by rachelmcr** [comment]
I confirmed that using `daysUntilClose: -1` worked fairly well for me in a test — it closed the issue an hour after marking it stale. An option to close it at the same time as being marked stale would still be useful, though.
