### ISSUE TITLE
Add additional reminder options

### ISSUE THREAD

**Issue by TheSalesOpsGuy** [probot/stale#139]
Currently StaleBot has the ability to mark an issue stale (and make a comment) and then after an additional amount of time comment again and close. Is there an appetite (and hopefully not a crazy lift) to add in the ability to make additional 'poke' comments? Something along the lines of `Stale at 14 days` then `+14 additional comment` then finally `+14 close and comment` (i'm personally asking for 1 more touch point but if multiple touches are possible I'd think a variable with the number of `pre-close` touches and messages would be better than adding in a single additional option.

**Comment by hiimbex** [comment]
I'm not sure I agree that stale issues need more than one bump, but I'm not opposed to adding additional options for things like this. However, I doubt anyone in our team will get to this any time soon if ever. But if you're interested in implementing this yourself, I'd happily review a PR!

**Comment by TheSalesOpsGuy** [comment]
That's fair (thanks for the response) the idea was along the lines of an initial `in danger of being stale` label that leads to a `stale` label and then finally gets closed, basically just moving things along in an attempt to get attention (for internal projects I'd love 2 warnings before closing instead of just a warning and a close message).

I'll take a look a the code, odds are its beyond my skillset but if I can make sense of it I'll see about making PR

**Comment by TheSalesOpsGuy** [comment]
Thanks StaleBot 🤖 	!

Closing this out for now, if I tackle a PR we'll revisit then 

༼ つ ◕ᴗ◕ ༽つ 🥞
