### ISSUE TITLE
Question about exemptLabels

### ISSUE THREAD

**Issue by RoySRose** [probot/stale#144]
Hello, Thank you for the bot.
I have a question on exemptLabels: option.

Will it work on the label with `:` included in the name?
I'm trying to use it on a label with the names such as `module:plugin`, `module:web`, .....

I'll really appreciate your response. Thank you.

**Comment by bkeepers** [comment]
Hey @RoySRose, it will work, but you'll need to quote the values due to yaml parsing:

```yml
exemptLabels:
  - "module:plugin"
  - "[Status] Maybe Later"
```

Let me know if that doesn't work for you.
