### ISSUE TITLE
Tests Fail When Running Locally

### ISSUE THREAD

**Issue by ragurney** [probot/stale#151]
I might be missing something obvious, but it looks like the test suite fails when running locally: 

**STR:**
1. Clone the repo
2. `npm install`
3. `npm test`

**Result:**
Both test suites fail with the message: "SecurityError: localStorage is not available for opaque origins"

**Fix:**
Adding
```js
  "jest": {
    "testURL": "http://localhost/"
  }
```
to `package.json` fixes the issue, as suggested in jsdom/jsdom#2304
fixes the issue. 

I'd be happy to open a PR for the fix if that's something you'd accept.

**Comment by hiimbex** [comment]
This was a recent jest change. I'd prefer the fix to use:
```js
"jest": {
  "testEnvironment": "node"
}
```

and would be happy to review such a PR!
