### ISSUE TITLE
daysUntilClose comment in example config file could be misinterpreted 

### ISSUE THREAD

**Issue by johlju** [probot/stale#153]
The config file in the README.md says `# Number of days of inactivity before a stale Issue or Pull Request is closed.`. This could be easily misinterpreted as it does not mention that the stale label must have been be set prior to this. Maybe we should update that comment to 

```
# Number of days of inactivity after the stale label has been set, before a stale Issue or Pull Request is closed.
```

**Comment by hiimbex** [comment]
Thanks for opening this issue @johlju! I totally agree with you. Wanna open a PR to propose that clarification?

**Comment by johlju** [comment]
@hiimbex happy to. proposed PR #156 for this issue.
