### ISSUE TITLE
Don't mark as stale when linked PRs are active

### ISSUE THREAD

**Issue by taquitos** [probot/stale#154]
Example: https://github.com/ruby-git/ruby-git/issues/355#issuecomment-408882358
There is work happening in a PR over the course of weeks, but the issue is marked as stale. Since the PR references the issue as a fix, perhaps the stale bot should make note of that and not mark it stale.

**Comment by JamesMGreene** [comment]
I think this concept definitely has merit. :+1:

My follow-up question is should this behavior still be in effect if the repo configuration for "stale" was only targeting issues (and *not* PRs)?

```
# Limit to only `issues`, not `pulls`
only: issues
```

If not, then a stale issue with an open associated PR (which may also be stale) will remain open forever, or until someone manually intervenes or changes the configuration.

**Comment by taquitos** [comment]
Oh, good point. 
I feel like you'd want it configured to look at both for the behavior I suggest. That end state you describe is really not desirable.
Alternatively, maybe having an extra explicit config flag that is essentially: `check_linked_prs_and_issues` (but having a better name) would be a decent approach?

**Comment by hiimbex** [comment]
I think this is a great idea! Any interest in opening a PR for this @taquitos?

**Comment by kunal-mohta** [comment]
I would like to work on this if @taquitos isn't already.

**Comment by kolaente** [comment]
Any updates on this?

**Comment by JamesMGreene** [comment]
Still relevant. 🙌
