### ISSUE TITLE
Processing less than 24 issues per day

### ISSUE THREAD

**Issue by dwijnand** [probot/stale#165]
The `limitPerRun` configuration option, which limits the number of actions per hour, has a minimum of 1.  This means that when enabling stale bot on a repo with lots of old issues, the minimum is getting pings on 24 issues per day.

Does anyone here have ideas how to reduce that?

I'm interested to know if it's possible to get somewhere between 1-5 issues a day, so that they can be reviewed appropriately.

Thanks!

**Comment by hiimbex** [comment]
You could fork stale and edit it's use of scheduler to utilize [these options](https://github.com/probot/scheduler#options).

Or you could build this into core stale and open a PR and as long as the default is still an hour, that should be fine.

**Comment by dwijnand** [comment]
From #167, this requires changes in probot's scheduler library.

As an alternative, can we find a configuration option to make probot's skip a run?  A blunt option would be "run once a day".  That would work for our use case, but would a change like that be accepted?

**Comment by dwijnand** [comment]
This is blocked pending an upstream fix of https://github.com/probot/scheduler/issues/32.

**Comment by ncw** [comment]
I note that you could do this in a probabilistic way without changing the scheduler by setting `limitPerRun = 0.1` and in the code if `limitPerRun < 0` compare it against a random number from 0..1 and if it is less than that number do the check, otherwise just return.
