### ISSUE TITLE
Feature request: Ignore issues written by a particular author

### ISSUE THREAD

**Issue by fainashalts** [probot/stale#173]
As a developer on my project, I sometimes use issues as a sort of to-do list. It would be great if I could ignore my own or my teammates' issues when determining what is stale. Something like an "exemptAuthors" array would be cool.

**Comment by christianbundy** [comment]
Same! I opened #172 to resolve this, which adds a bit of flexibility by using the assignee rather than the original author (which allows issues to be transferred). Do you think this would fulfill your feature request?

**Comment by fainashalts** [comment]
@christianbundy I looked at #172 and just want to make sure I understand -- does this mean that if the issue is assigned to someone it cannot be marked as stale? Its not exactly what I had in mind but would be very helpful too!

**Comment by christianbundy** [comment]
Yep, exactly. The two benefits are:

- You can keep an issue authored by a non-member from going stale by assigning someone to it.
- You can let an issue go stale by unassigning everyone from it, regardless of who authored it.

**Comment by fainashalts** [comment]
Great! Thanks for adding this. I look forward to when it gets merged!

**Comment by fainashalts** [comment]
@christianbundy is this feature available yet? I'd love to add it to my implementation of stalebot. Thanks, please let me know!

**Comment by christianbundy** [comment]
Yep, it's used like this:

```yml
# Set to true to ignore issues with an assignee (defaults to false)
exemptAssignees: true
```

As long as there's an assignee the issue will be kept safe from stale[bot].

**Comment by fainashalts** [comment]
Thanks @christianbundy! Using this feature now, it is much appreciated!
