### ISSUE TITLE
Only two PR got marked as Stale

### ISSUE THREAD

**Issue by SaraVieira** [probot/stale#179]
👋

We are using Stale at CodeSandbox and after installing it only marked two PR has stale even though there are a lot of issues from 2017. I tried to debug it but I'm not sure what is up

I also ran the file through a YAML validator and it turned up okay:
https://github.com/CompuIves/codesandbox-client/blob/master/.github/stale.yml

You can see here tons of issues from 2017 
https://github.com/CompuIves/codesandbox-client/issues?page=15&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

Any ideas ?

Thank You

**Comment by JasonEtco** [comment]
Hiya! Thanks for the details, and for the check on your YAML file.

Stale has a "timer", where despite being installed correctly it intentionally takes a slow-and-steady approach (especially on big repositories) to prevent any rate-limiting issues. This often looks like it just isn't doing anything.

My advice is to wait it out - I see this issue has been open for a couple of days, so I'm hoping its all resolved and working as expected 🤞 if that isn't the case, please let me know and I can look into it!

**Comment by JasonEtco** [comment]
Sorry for the double post - I've done some more digging, thanks for the links to your repo. Turns out we're having some memory usage issues in the deployed application. Hopefully we'll get em resolved this week! I know its not an ideal solution, but in the meantime you're welcome to [host your own deployment of Stale](https://github.com/probot/stale/blob/master/docs/deploy.md) :smile: Thanks for your patience 🙏

**Comment by SaraVieira** [comment]
Hey!

Since we have such a big repo it does make sense for us to deploy it so we get it off your hands.

I will try GH actions and close this issue :)

I will post here if I have any issues!


Thank you for your help :D

**Comment by mboersma** [comment]
We are having a similar issue as far as I can tell for the https://github.com/Azure/acs-engine repository. 
It has a seemingly valid [stale.yaml](https://github.com/Azure/acs-engine/blob/master/.github/stale.yaml) but has never seen any attention from the hosted bot.

Whereas the newer aks-engine has a similar [stale.yaml](https://github.com/Azure/aks-engine/blob/master/.github/stale.yaml) that does appear to be working. I can't tell what the difference might be, so I wonder if it has to do with the memory usage issues @JasonEtco referred to.
