### ISSUE TITLE
newrelic broke our bot

### ISSUE THREAD

**Issue by grrowl** [probot/stale#188]
https://github.com/probot/stale/pull/185/files#diff-168726dbe96b3ce427e7fedce31bb0bcR1 adds `require('newrelic')`, but we self-host and don't have newrelic, so now our bot doesn't start.

https://github.com/probot/stale/blob/b8e5343941d00ba1f0902ae58bb10cdfa1399f47/index.js#L1

**Comment by grrowl** [comment]
actually it is a dependency of `probot-stale`, so it's not this package. will continue hunting, sorry!

**Comment by sohymg** [comment]
how do we turn off newrelic if we self-host?

**Comment by tknickman** [comment]
@sohymg I have addressed this in https://github.com/probot/stale/pull/198. Hopefully that will work for you!
