### ISSUE TITLE
Feature Request: @mentions for the issue author

### ISSUE THREAD

**Issue by designsimply** [probot/stale#190]
Any chance it would be possible to have a generic way to @mention the post author in the `markComment` field?

It would be really cool to be able to say something like:

> @bkeepers, is this still relevant? If so, would you mind leaving a comment with additional details?

**Comment by nventuro** [comment]
Came here looking for this very thing, such a feature would go a long way towards making the bot friendlier imo.

**Comment by nventuro** [comment]
I'm assuming this isn't very hard to pull off, and I'm willing to do it myself, but would love some pointers regarding where to look at to achieve this.

**Comment by designsimply** [comment]
Still relevant! Need some direction + pointers. 🙂
