### ISSUE TITLE
Require config to enable integration

### ISSUE THREAD

**Issue by bkeepers** [probot/stale#2]
From the README:

> **Heads Up!** This integration will run as soon as you install it on your repository. If you want to change any of the settings, do it before installing.

Right now, when this integration is installed, it will immediately run on all repositories that it has access to using the [default](https://github.com/probot/stale/blob/master/lib/defaults.js) configuration, which means every issue older than 60 days gets commented on and labeled.

This can be a little jarring, so I'm wondering if it should require `.github/stale.yml` to at least be present to run.

Thoughts?

@zeke @lee-dohm @parkr

**Comment by lee-dohm** [comment]
I think that's a good idea. I feel like all integrations should default to no action until the integrator takes an affirmative action to approve a configuration, even if it is the default.

**Comment by bkeepers** [comment]
#4 puts probot into "dry-run" mode for repos without a config. It needs to be updated to just not try to run at all, but I'm about to jump on a ✈️, so that's a temporary solution.

**Comment by bkeepers** [comment]
The changes in #4 have been working fine. There needs to be some tweaks based on #29, and it'd be awesome if the config was added in a PR as suggested in #9, but I don't think and further changes are required here.
