### ISSUE TITLE
Feature Request: Option to comment on an issue when the "stale" label is removed

### ISSUE THREAD

**Issue by rallytime** [probot/stale#20]
First off, thank you for this great service. I'm testing this out on one of the repositories that I help maintain and it has already been really useful.

Secondly, it would be great if there were an option for the bot to comment on an issue when the `stale` label is removed due to the issue being updated. Just something like "Thanks for commenting. This issue is no longer marked as stale."

**Comment by bkeepers** [comment]
Thanks for the suggestion!

**Comment by rallytime** [comment]
Thanks for adding this so quickly!
