### ISSUE TITLE
stale bot appears to not be running for our test repo

### ISSUE THREAD

**Issue by erikvold** [probot/stale#202]
We'd like to use stale bot to auto close (with a message) any pr on a repo.  We setup a test repo yesterday to test things out and see how/if it works at https://github.com/hfiguiere/migration-test/pulls and these pull requests haven't been touched by the bot yet in about 23hrs, and we're expecting/hoping the bot to close and comment on these two pull requests within an hour.

Any ideas what we might have to do to get this running?

**Comment by erikvold** [comment]
This is the config we are testing with https://github.com/hfiguiere/migration-test/blob/master/.github/stale.yaml

**Comment by hfiguiere** [comment]
it has never worked

**Comment by ssbarnea** [comment]
I am quire curious because I have a similar experience, where after enabling the app and adding the config file nothing is happening, even if I have tickets that are years old. No feedback at all, even after almost 24h.

**Comment by NorrinRadd** [comment]
I have the same problem.  The app does not seem to be running for me.

**Comment by eysi09** [comment]
Same. I have Stalebot installed and here's the config: https://github.com/garden-io/garden/blob/master/.github/stale.yaml. But so far, nothing has happened.

**Comment by cruzach** [comment]
Anyone figured out what causes this?

**Comment by hfiguiere** [comment]
Apparently the stale bot work on itself.

**Comment by leviem1** [comment]
@hfiguiere stale.yaml != stale.yml 😉

**Comment by ojab** [comment]
Looks like it needs to be explicitly enabled in https://github.com/apps/stale/installations/863906 at least in some cases.
