### ISSUE TITLE
Stale is not working

### ISSUE THREAD

**Issue by Ovilia** [probot/stale#208]
I've installed stale on https://github.com/apache/incubator-echarts two days ago.
<img width="488" alt="屏幕快照 2019-06-06 10 50 11" src="https://user-images.githubusercontent.com/779050/59003548-06d31e00-8849-11e9-9d91-fb7181937cbf.png">

But it's not adding `stale` label. The config file is at https://github.com/apache/incubator-echarts/blob/master/.github/stale.yml 
Please help have a look. Thanks!

**Comment by Ovilia** [comment]
Any update on this?

**Comment by AdmiringWorm** [comment]
It isn't odd that it haven't closed marked any issues for you.
You have configured the stale bot to only mark open issues older than 2 years as stale, but you don't have any issues that old: https://github.com/apache/incubator-echarts/issues?q=is%3Aopen+updated%3A%3C2017-06-23

**Comment by Ovilia** [comment]
But there are many issues older than 2 years, like this one: https://github.com/apache/incubator-echarts/issues/2426

**Comment by Ovilia** [comment]
I tried with this filter https://github.com/apache/incubator-echarts/issues?utf8=%E2%9C%93&q=updated%3A%3C2018-10-10+is%3Aopen+ and it only works for date after 2018-10-10. That's weired because there are many issues older than that.

**Comment by Ovilia** [comment]
It's still not working for me. But I guess it doesn't matter much now.
