### ISSUE TITLE
Custom probot instance doesn't pick up repositories after stale.yml is added

### ISSUE THREAD

**Issue by scherniavsky** [probot/stale#212]
Hi,
First of all, thanks for the nice tool!

I run a custom Probot-stale instance with GitHub Enterprise. When I add it for an organization Probot schedules all repos (`Scheduling interval` in logs) and then de-schedules those where the stale.yml files are not found (`Canceling interval`).

The problem appears when I add `stale.yml` config to a repo after it has already been de-scheduled - it never gets scheduled again until I restart the Probot (tried to wait for 3 days).

In the logs I can see that Probot detects that the config file is there:
```
GitHub request: GET /repos/:owner/:repo/contents/:path - 200 OK
params: {
"owner": "my_org",
"repo": "testrepo",
"path": ".github/stale.yml",
...
```
nevertheless the `Scheduling interval` line never appears again and existing issues don't get marked.

Please advise.

**Comment by ojacques** [comment]
@scherniavsky - I have the same issue: need to restart probot to get it to pick up repos that were de-scheduled. 
Looking at [the code](https://github.com/probot/stale/blob/master/index.js#L54), it uses `probot-config` to get the stale.yml file. I initially thought that this file could be cached, leading to the problem. But https://github.com/probot/probot-config/issues/32 tells me its not cached.

@tcbyrd - have you observed this too?

**Comment by cyberhck** [comment]
No, it's not cached, I'm also experiencing this on my private instance. It's because when it doesn't find the .stale.yml file, it de-schedules those, but once descheduled, it never gets picked up.

**Comment by cyberhck** [comment]
Noooo
