### ISSUE TITLE
Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

### ISSUE THREAD

**Issue by StingyJack** [probot/stale#214]
Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

_Originally posted by @stale in https://github.com/probot/stale/issues/147#issuecomment-503797673_

YES It's still relevant. Figure it out @stale, since you so useful

**Comment by BlueHatbRit** [comment]
I think discussion should really stay in my issue that you pointed to, that way it can be kept all in one place. One of the maintainers mentioned that they like the idea but it's not a priority for them to build, but they'll happily help someone else build it. If you submit a PR I imagine you'd get some great feedback.
