### ISSUE TITLE
Report `daysUntilClose` (human readable) to the user when threatening to close issues

### ISSUE THREAD

**Issue by jsoref** [probot/stale#215]
This antisocial bot is incredibly unhelpful in its rude behavior.

If a bot is going to threaten to take an action, it should be so kind as to tell everyone when it plans to take that action instead of merely saying "hey, i'm going to do something at some point."

The bot generally speaking doesn't touch issues for months, and yet its default is to kill issues after a week. It's totally reasonable for someone to be away for a week, or if they're European for an entire month. 

I'd suggest that it report both a relative date (preferably in human readable terms -- 14 days => 2 weeks) and an absolute date (again, human readable -- i.e. not seconds since the epoch.)

**Comment by mdinos** [comment]
Why not just add this to your own configuration?

**Comment by jsoref** [comment]
Because it's not my app? I'm the victim here and I want you to fix it generically so that each GitHub project I visit which chooses to use your app provides me with a better experience?

Why blame the victim?

**Comment by mdinos** [comment]
I'm not the owner of this repo.. I'm just suggesting that this could increase the complexity of the code, and add very little value - you can configure your own comments through the very simple configuration file, and can you not trust your developers to count 7 days into the future?

```
markComment: >
   This will be deleted in 7 days due to inactivity.
```

It doesn't have to be rude, just like you don't have to be rude to me. Please don't get angry and victimise yourself, I'm trying to have a discussion.

As a side, the maintainer of this repo appears to have abandoned it, you're unlikely to get any requests into the code.

**Comment by jsoref** [comment]
That bot is really passive aggressive.

**Comment by jsoref** [comment]
It's still an absolutely unfriendly bot.

**Comment by jsoref** [comment]
It's still an absolutely unfriendly bot.
