### ISSUE TITLE
Not active

### ISSUE THREAD

**Issue by GregTheGreek** [probot/stale#216]
Hi all  - its been a few days and stalebot doesn't seem to have done anything yet. I saw the readme said to just make an issue, our repo is: https://github.com/ChainSafe/lodestar

**Comment by anthonylavado** [comment]
@GregTheGreek I'm not from the Probot org, but a quick check of your YML makes me think this line is wrong:
https://github.com/ChainSafe/lodestar/blob/aa55f2803e02488ae61e2e8ca650f3d1c176ebe4/.github/stale.yml#L14

As a result, the config is technically "invalid". Does that sound about right?
