### ISSUE TITLE
Not seeing any bot activity

### ISSUE THREAD

**Issue by sbc100** [probot/stale#230]
I setup stale about 24 hours ago but I'm not seeing any activity:

https://github.com/emscripten-core/emscripten/blob/incoming/.github/stale.yaml

Do you I just need to wait?   Or did I do something wrong?  Perhaps our daysUntilStale of 730 is unusually high?

**Comment by sbc100** [comment]
The fix was to make sure that file ends with ".yml" and not ".yaml".  Doh!

**Comment by zeke** [comment]
Thanks for following up, @sbc100 👍

**Comment by sbc100** [comment]
I got a kick of out this ironic stale bot comment: https://github.com/emscripten-core/emscripten/issues/4012
