### ISSUE TITLE
Can't comment on locked issues

### ISSUE THREAD

**Issue by bkeepers** [probot/stale#25]
https://sentry.io/bkeepers/probot/issues/269778295/

```
Error: {"message":"Unable to create comment because issue is locked.","documentation_url":"https://help.github.com/articles/locking-conversations/"}

Error: {"message":"Unable to create comment because issue is locked.","documentation_url":"https://help.github.com/articles/locking-conversations/"}
```

cc @lee-dohm

**Comment by lee-dohm** [comment]
We should investigate a better solution than just ignoring them.

**Comment by bkeepers** [comment]
I think ignoring locked issues is fine for now. There's not much we can do with the locked issue anyway. Feel free to chime in if you disagree.

**Comment by dessant** [comment]
We have resorted to unlocking, commenting and then relocking with one of our bots:
https://github.com/kivy/kivy/issues/5560

The ideal solution would be to have a GitHub API permission type which would give bots a way to comment on locked threads, possibly also overriding temporary interaction limits, like a collaborator can.
