### ISSUE TITLE
Latest version of probot causes error when getting config

### ISSUE THREAD

**Issue by jakeswenson** [probot/stale#254]
The current probot code is expecting for `context.config` call to error if no config is found, but the current version doesn't seem to error when no config is defined an instead i am getting this error:
```
20:56:12.254Z ERROR probot: Cannot convert undefined or null to object
  TypeError: Cannot convert undefined or null to object
      at Function.assign (<anonymous>)
      at forRepository (/bot/node_modules/probot-stale/index.js:53:21)
```

Looking at that line I see:
![image](https://user-images.githubusercontent.com/1854799/68430903-ded44780-0165-11ea-871a-841cf479944d.png)

Seems like it should supply that default config if it's null or undefined as well.

**Comment by jakeswenson** [comment]
Same here, need the latest version published to NPM registry

**Comment by jakeswenson** [comment]
@JasonEtco ^

**Comment by jakeswenson** [comment]
Both this and #253 are probably fixed in master, but the changed need to be published to NPM

**Comment by rthadur** [comment]
@jakeswenson did you find solution ?
