### ISSUE TITLE
Add background color to the Stale label

### ISSUE THREAD

**Issue by andreamussap** [probot/stale#257]
Hi, community! First of all, thanks for creating this helpful app. We've just installed it in our [project](https://github.com/Axway/axway-open-docs/projects/1) and I think it's going to be very helpful.

I'd like to ask you though if it's possible to add a style/color to the `Stale` label so it would be more visible when the ticket is in the board:

![staleLabelStyle](https://user-images.githubusercontent.com/10401080/72808443-77507300-3c51-11ea-8499-cc25908702f7.jpg)

Thanks!!

**Comment by geerlingguy** [comment]
@andreamussap - You can edit the label in your GitHub project and change the color there: https://help.github.com/en/github/managing-your-work-on-github/editing-a-label
