### ISSUE TITLE
Triggering abuse detection

### ISSUE THREAD

**Issue by bkeepers** [probot/stale#26]
@lee-dohm installed the stale plugin on @atom. I'll need to dig into why this triggered the abuse detection.

https://sentry.io/bkeepers/probot/issues/269777963/

```
Error: {"message":"You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.","documentation_url":"https://developer.github.com/v3#abuse-rate-limits"}
```

**Comment by bkeepers** [comment]
This happened again when @hzoo added it to https://github.com/babel/babel.github.io/issues

**Comment by bkeepers** [comment]
Another idea that came up while @lee-dohm and I were talking that might help solve this and reduce complaints from end-users is to artificially limit the number of issues that can be marked in one run. For example, if it only marked 5 during each hourly run, then it would avoid abuse issues, and might not seem as aggressive to contributors.

**Comment by ungb** [comment]
+1 on the issue https://github.com/probot/stale/issues/59.  I saw a bunch of issues getting closed on atom after 14 days after it got marked as stale but no comment was added.

example:
https://github.com/atom/atom/issues/10831
https://github.com/atom/atom/issues/12308
https://github.com/atom/atom/issues/8880

There's a lot more.

**Comment by bkeepers** [comment]
https://sentry.io/probot/stale/issues/378133484/
