### ISSUE TITLE
Stale posted a comment to, and labeled, an issue that was already closed

### ISSUE THREAD

**Issue by aviflax** [probot/stale#263]
This one: https://github.com/FundingCircle/fc4-framework/issues/243

My config is here: https://github.com/FundingCircle/fc4-framework/blob/33771d469e9b6b8475541fee0e29ab9ccec7a417/.github/stale.yml (that’s my current HEAD of master but I wanted to share a stable URL)

Is there anything I could to do prevent this?

Thank you!

**Comment by tyll** [comment]
Just saw this in a merged PR: https://github.com/nmstate/nmstate/pull/871#issuecomment-598188414

**Comment by JamesMGreene** [comment]
I didn't see anything suspect in the codebase (though I'm admittedly not_ super_ familiar with it) so I almost wonder if it was a temporary issue with the GitHub Search API or something...? 🤔

**Comment by aviflax** [comment]
> so I almost wonder if it was a temporary issue with the GitHub Search API or something...? 🤔

I’ve seen things like this happen with GitHub, so yeah, this is definitely plausible. Likely, even, it seems to me.

Would it be crazy for the bot to double-check the state of the issue right before acting on it?

**Comment by JamesMGreene** [comment]
Working on it. 👍
