### ISSUE TITLE
Run Stale without stale.yml

### ISSUE THREAD

**Issue by the21st** [probot/stale#264]
Hi! I wanted to add Stale to our org, but we have tens of repos and it's too much effort adding the `stale.yml` config file to each one. Could Stale work off a default setting for all org repos?

I really liked the onboarding of https://probot.github.io/apps/delete-merged-branch/ where I just added it and it automatically works for all repos.

**Comment by diwakergupta** [comment]
I'm interested in this as well. Per the documentation at https://probot.github.io/docs/best-practices/#store-configuration-in-the-repository, it *should* work:

> If configuration for your app is not available in the target repository, it will be loaded from the .github directory of the target organization's .github repository.

I'm going to try this and see if it actually does. @the21st would appreciate if you could give that a spin too.

**Comment by rthadur** [comment]
@diwakergupta were you able to run this successfully , I want to include stale.yml file in current project.
