### ISSUE TITLE
Stalebot commenting on closed issues & marking as stale

### ISSUE THREAD

**Issue by max-sixty** [probot/stale#273]
FYI: https://github.com/pydata/xarray/issues/2094

Thanks!

**Comment by mlampros** [comment]
Thank you for making 'stale' publicly available. I want also to report the same for [SuperpixelImageSegmentation/issues/2](https://github.com/mlampros/SuperpixelImageSegmentation/issues/2)

**Comment by JamesMGreene** [comment]
This should be fixed by PR #269.

**Comment by JasonEtco** [comment]
Closed by #269
