### ISSUE TITLE
How much does this costs?

### ISSUE THREAD

**Issue by sblantipodi** [probot/stale#281]
Hi,
I would like to activate this app on my repos, when I try to activate it it says that it is free
Prorated for May 23rd-Jun 22nd

How much it will cost after jun 22nd?

thanks.

**Comment by leviem1** [comment]
It should remain free. There's no cost (at least that I'm aware of, but I could be wrong) and it doesn't look like there's any plan to introduce it. That being said, I'm just a random user, but I guess it's better than silence?
