### ISSUE TITLE
Does the bot reopen issues/PR when there is some actvity?

### ISSUE THREAD

**Issue by kartik1000** [probot/stale#282]
Hello, I have been using stale-bot for quite some-time now. But I am facing an issue that the bot is not able to automatically reopen the issues when someone makes some comments or activity occurs. I saw that this one of the listed features in the GitHub marketplace.
https://github.com/apps/stale
But I could not find anything related to it in .yml file and by default, it is not enabled. Am I maybe missing something in my settings or config file? Can anyone let me know about this? Maybe @JasonEtco? I will be highly obliged and thankful.

**Comment by stephenpaulger** [comment]
From reading the code the bot doesn't unmark issues as stale when there is activity before closure, though there is a function named `unmark()` it is never called. The bot does not do anything with closed issues.

So, no, there is no re-opening and no unmarking.

**Comment by kartik1000** [comment]
I am not sure But I think the unmark function is used to unmark stale pull requests/issues when there is some activity after the issues/Pr is marked stale but not closed.

**Comment by stephenpaulger** [comment]
@kartik1000 yes, you're right sorry it is called from index.js https://github.com/probot/stale/blob/e3c53ebf879cccaf856fba1602fdd67f878c3ee3/index.js#L20

I'll update my other comment to correct it.
