### ISSUE TITLE
Inconsistent handling of dry run flag

### ISSUE THREAD

**Issue by stkent** [probot/stale#29]
`stale.markAndSweep` _never_ appears to be [executed](https://github.com/probot/stale/blob/18b4d383a275c504d4b434833a2acfb176ba26eb/index.js#L51) when we're performing a dry run. However, some methods invoked by `stale.markAndSweep` themselves perform [logging](https://github.com/probot/stale/blob/18b4d383a275c504d4b434833a2acfb176ba26eb/lib/stale.js#L59-L68) during dry runs _only_. It's not clear to me that these statements will ever be reached. What am I missing?

**Comment by bkeepers** [comment]
@stkent yep, looks like you are correct. I think at some point I switched it from "do a dry run even if there's not config" to "OMG preserve API requests wherever possible".

There's not a way for anyone to see the results of the dry run besides from the console, so I'm debating about just removing the dry run feature and instead replace it with some better on-boarding features that open a PR on the repo with the config and links to the issues that will be marked as stale.

Thoughts?

**Comment by stkent** [comment]
Those suggestions make a lot of sense from the perspective of end users, for sure! I'm not sure they replace the functionality of an explicit dry run flag for plugin developers, however; I'm not sure what I'd suggest for that case... 🤔

**Comment by astrofrog** [comment]
As a developer, I would really like a way to test this that doesn't involve opening an issue or pull request, so I'm in favor of keeping the ability to do a dry run from the console.
