### ISSUE TITLE
Make feature_request label configurable

### ISSUE THREAD

**Issue by andig** [probot/stale#290]
I'm already using "Enhancement" as label for feature requests plus don't personally like the look of the _ in the name as it does not match other label's style. Searching the codebase for `feature_request` didn't return any results- would be great to understand where this comes from plus make it configurable.

**Comment by kennethtran93** [comment]
@andig are you sure you're asking this in the correct repo?  I don't think this belongs here.

**Comment by andig** [comment]
Thank you.. migrated to https://github.com/machine-learning-apps/Issue-Label-Bot/issues/75

**Comment by Shauntct17** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
