### ISSUE TITLE
Stale bot not running

### ISSUE THREAD

**Issue by shekhar-shubhendu** [probot/stale#297]
I have setup the bot on a project but it does not seem to run, tried removing and adding again too.

Here is the stale.yml https://github.com/react-cropper/react-cropper/blob/develop/.github/stale.yml

**Comment by scalp42** [comment]
@shekhar-shubhendu what was the fix? Running into the same issue.

**Comment by shekhar-shubhendu** [comment]
@scalp42 For me, the issue was with YAML formatting. It worked after I fixed it.
