### ISSUE TITLE
Adding multiple labels at once triggers duplicate remove label calls

### ISSUE THREAD

**Issue by stkent** [probot/stale#30]
If I have a stale issue, then apply several new labels at once (here the `security` label is exempt, and the other two labels are not), I see multiple attempts to remove the label in the logs, and several of those attempts fail because the label has already been removed:

<img width="504" alt="screen shot 2017-05-22 at 2 49 31 pm" src="https://cloud.githubusercontent.com/assets/6463980/26312018/2115c006-3efe-11e7-9fa0-de7a19917ec8.png">
<img width="1051" alt="screen shot 2017-05-22 at 2 50 39 pm" src="https://cloud.githubusercontent.com/assets/6463980/26312019/2132eb0e-3efe-11e7-8d45-7d3717fdbe73.png">

Not sure if this is particularly important since the outcome is as desired; just reporting for reference.

**Comment by bkeepers** [comment]
@stkent thanks for the report. I'm guessing there are multiple webhooks delivered at once. The workaround for this would be very interesting.
