### ISSUE TITLE
Clarify what is meant by 'inactive'

### ISSUE THREAD

**Issue by astrofrog** [probot/stale#34]
It would be good to be explicit about what constitutes activity. For example, does adding a label constitute activity? Or changing a milestone? In my case I would like to be able to configure this to say that I specifically want activity to be linked either to a pushed commit or a comment, but ignore changes in labels, milestones and other such events. Is there a way this could be done?

**Comment by rallytime** [comment]
Hi @astrofrog - I don't think there is any way to specify this right now. The bot currently uses the [updated](https://help.github.com/articles/searching-issues/#search-based-on-when-an-issue-or-pull-request-was-created-or-last-updated) search option as seen [here](https://github.com/probot/stale/blob/08ce8fd6c91dcce348fda478b3587b4824f728d9/lib/stale.js#L41), which includes changes in milestones and labels as you've discovered.

I ran into confusion about this myself, as I wasn't sure if just a comment was the last event the bot looked for or not on issues, for example.

@bkeepers has asked me to get some docs together about this to clarify the `updated` confusion. However, I don't know if filtering these events would be possible to add. I think it's a nice idea. What do you think @bkeepers?

**Comment by bkeepers** [comment]
Hey @astrofrog, great question. Per @rallytime's explanation, the plugin delegates to GitHub for determining updated time.

> However, I don't know if filtering these events would be possible to add. I think it's a nice idea. What do you think @bkeepers?

It would be possible by fetching the timeline for each issue and filtering out the events you don't care about, but with the current implementation will require a lot of API requests. Switching to GraphQL (which I'd like to do sooner or later), might make it better. I'd be happy to review a PR that makes these changes, but probably won't be working on it myself anytime soon.

I think the doc updates that @rallytime is working on will at least help clarify current behavior.

**Comment by bkeepers** [comment]
This was clarified in #41. Let me know if that helps!
