### ISSUE TITLE
Make it easier to tell if the bot is running

### ISSUE THREAD

**Issue by rallytime** [probot/stale#36]
If you use the GH integration, or even if you're running the bot yourself, it's a little difficult to tell if it's working or not. Documenting some of the default behavior and what to look for when troubleshooting as #35 suggests will certainly help, but it'd be great to get some feedback either when the bot starts up or the GH integration is configured/installed.

An idea to improve the on-boarding experience: auto-open an issue/PR somewhere that gives feedback that the integration was installed properly (whether through GH, or when you start the bot on your own hosted service installation).

One thing that I found useful for me was when I realized the bot uses the `updated` tag, I added that to the issue search bar to see what date made sense to set the initial `daysUntilStale` value to. Maybe this feature could use that value in the auto-open issue/PR comment to link to the issues (or prs) that would be set as stale when the bot starts running? That way people can see "oh, this is working, great!" and "Hrm...when I click this link, no issues are in that list." or whatever the case may be. 

Something like:
```
Probot-stale has been configured for the <x> repo. 

<Something about whether or not a config file was found, and what probot-stale will do in either case.>

Within the next hour, probot-stale will comment on <y> issues and <z> PRs. You can see the list of issues [here](<link to repo's stale issues>) and the list of PRs [here](<link to repo's stale PRs>).

If you need to updated your config file based on the findings listed above, note that probot-stale will run as soon as changes to the `stale.yml` file are merged into the main repository branch.
```

I am not sure if this would be better to have the issue/PR auto-open on the repo with the config, or on some kind of "demo" repo. I don't know the code well enough or how integrations work, but either way I think it would be helpful for people to get started.

**Comment by MatteoGabriele** [comment]
it's hilarious that this ticket has been closed by a bot
