### ISSUE TITLE
Instead of blacklisting labels, allow to whitelist

### ISSUE THREAD

**Issue by felixfbecker** [probot/stale#42]
At https://github.com/sequelize/sequelize we have a lot of long standing issues that are indeed valid feature requests and have a lot of valuable discussion on it. But almost all features come from contributions, as most features are complex and we maintainers don't have time to implement it if we don't need it.
But the majority of issues are support issues that are missing info or questions.
I would like to start by automatically closing stale issues that have the "needs more info" label instead of closing all issues _except_ specific labels.

**Comment by bkeepers** [comment]
Thanks for the suggestion. Closing as a duplicate of https://github.com/probot/stale/issues/22, which has a PR in progress.
