### ISSUE TITLE
question: probot not closing issues

### ISSUE THREAD

**Issue by SD10** [probot/stale#43]
We're currently using probot/stale at [Moya](https://github.com/Moya/Moya) and the bot is marking issues as stale but not returning to close them after the specified `daysUntilClose` setting.

Can anyone help troubleshoot this issue? You can find the `stale.yml` file [here](https://github.com/Moya/Moya/blob/master/.github/stale.yml)

I'm aware that probot uses the updated search qualifier to find stale issues and pull requests, but none of the issues that were marked stale have been modified since.

Any help would be greatly appreciated 😅

**Comment by bkeepers** [comment]
Hey @SD10, sorry for the delay in replying here. I've been on vacation and completely ignoring the internet. It looks like your fix in #44 should resolve this, but let me know if you have any other issues.

Thanks for reporting the issue and taking time to fix it!
