### ISSUE TITLE
Probot-stale seems to not be working

### ISSUE THREAD

**Issue by rallytime** [probot/stale#51]
@bkeepers It appears that the stale bot isn't working. GitHub's APP server and API status says it is all good, but when I click the link listed at the top of the repo, I get a 404 Error:

https://github.com/apps/probot-stale

Based on my settings in my stale config file, there are about 4 days of issues that should have been marked as stale, but have not received the `stale` label or a bot comment. There are also issues open that were marked as stale 11 days ago, but have not been closed or updated in any way (we're using the default setting of 7 for the `daysUntilClose` option).

**Comment by bkeepers** [comment]
Hey @rallytime

> when I click the link listed at the top of the repo, I get a 404 Error:
>
> https://github.com/apps/probot-stale

Sorry, I renamed the app this morning to be consistent with the other Probot apps that are being shipped and forgot to update the link in the repo. It's been updated now: https://github.com/apps/stale

> Based on my settings in my stale config file, there are about 4 days of issues that should have been marked as stale, but have not received the `stale` label or a bot comment. 

Can you link to the repo that you're having issues with? It looks like it's working on some repositories:

- https://github.com/exercism/ruby/issues/666#issuecomment-320968776
- https://github.com/exercism/ecmascript/issues/303

**Comment by rallytime** [comment]
@bkeepers Oh, yes. Here's the list of stale issues that have been marked recently as stale, but not closed: https://github.com/saltstack/salt/issues/13681

And here is the stale config: https://github.com/saltstack/salt/blob/develop/.github/stale.yml

We are slowly updating our `daysUntilStale` value, which is rather large, so we don't close a ton of issues all at once. It appears that the bot ran when that the new value was changed from `1145` to `1130` in https://github.com/saltstack/salt/commit/64ae7e4475552f12722e0e6e9638bc17bb78897a 11 days ago, but looks like it hasn't done much since then.

**Comment by rallytime** [comment]
Ah I just realized I only linked a single issue. Here's the list of issues that were marked as stale, but not closed: https://github.com/saltstack/salt/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Astale%20

**Comment by bkeepers** [comment]
@rallytime it doesn't look like the stale app is installed on the @saltstack org. Does it show that it is when you visit https://github.com/apps/stale/installations/new?

**Comment by rallytime** [comment]
@bkeepers Yes, it does show up there with `Configure` before the `>` for the SaltStack organization. It also shows up in the "Installed GitHub Apps" section of the SaltStack organization settings. We're also using it on another repo in the org: https://github.com/saltstack/salt-bootstrap

The salt-bootstrap repo isn't as active as the salt repo, but the last activity we had there was in this issue: https://github.com/saltstack/salt-bootstrap/issues/880. I don't think there should have been anything else active for the stale bot since then, though.

Here is a screenshot of the org's settings for the `Probot: Stale` installation:

![screen shot 2017-08-09 at 9 41 15 am](https://user-images.githubusercontent.com/6547906/29124607-5fee2616-7ce7-11e7-9114-1e4dd6651ddc.png)

**Comment by bkeepers** [comment]
@rallytime ok, I've figured out the issue (`/integration/installations` API [now redirects](https://developer.github.com/changes/2017-07-19-removal-of-integrations-routes/) to `/app/installations` and loses pagination information). It's going to require an update to the [node-github](https://github.com/mikedeboer/node-github) client, which might take a day or so.

Thanks for reporting the issue, and thanks for your patience.  On the bright side, this app has >100 installations now. Unfortunately, it only works for the 100 most recent.

**Comment by rallytime** [comment]
@bkeepers No problem! I'm glad you were able to discover the issue and that is also fantastic that there are >100 installations. 🎉

**Comment by bkeepers** [comment]
@rallytime This is _finally_ resolved. Thanks for your patience while I worked through days of debugging trying to uncover the issue.

**Comment by rallytime** [comment]
Great! Thanks @bkeepers!
