### ISSUE TITLE
npm version out of date

### ISSUE THREAD

**Issue by BlueHatbRit** [probot/stale#55]
I'm trying to use probot-stale as a plugin to a large bespoke bot but I just realised that the version on npm is 5 months old and using "probot-visitor" which is causing a bunch of errors. I'm assuming this is because that module has been renamed to "probot-scheduler" quite a while ago and had numerous updates to it.

Would it be possible to bump the package version of this module and publish it to npm again? That would make this usable as a plugin again.

**Comment by hiimbex** [comment]
@bkeepers the [npm module](https://www.npmjs.com/package/probot-stale) also references the old name.

Also @BlueHatbRit just curious, but what's the use case of your bot with stale as a plugin? Typically people use our [deployed version](https://github.com/apps/stale). It's a plugin as well obviously, but I'm just super curious what your additions or integrations of it are? :D

In the meantime, you can install it via the current code on this repo. I always forget the syntax for this, but here's the [npm docs on how to do it](https://docs.npmjs.com/files/package.json#github-urls).

**Comment by BlueHatbRit** [comment]
@hiimbex, yeah I've setup using just a simple git reference to a specific hash for now, it'd be good to get some up-to-date npm module version though.

I'm wrapping up a few of public probot actions + some of my own and I figured it'd be nice to have them all under one application which can be branded up with it's own name, image, etc. Right now I'm mostly trying to test our probot and see how easy it is to mix and match plugins and mash them together. The documentation is a little thin in how probot works as a whole so I'm doing some experimentation to see how plugin loading works and such.

**Comment by hiimbex** [comment]
Awesome! 

>  it'd be good to get some up-to-date npm module version though.

Totally agree. I'm just not in charge of the npm module 😜, but I'm quite certain Brandon will update it when he has a minute.

> The documentation is a little thin in how probot works as a whole

Please feel free to add any documentation you think helps clarify things or open issues for things you think need clarification. We are currently in an overhaul 🛠 👊🏼 of our docs, but I think the best place to look right now is [probot.github.io/docs](https://probot.github.io/docs/). If you run into things you find frustrating or annoying, please open an issue in [probot/friction](https://github.com/probot/friction) to help us iterate and improve ☺️

**Comment by BlueHatbRit** [comment]
> Totally agree. I'm just not in charge of the npm module 😜, but I'm quite certain Brandon will update it when he has a minute.

Cool, hopefully it won't too much work. I'd be happy to issue a PR if there are any small jobs that can be identified to get this published again. Though it looks like it should just be a case of bumping the version number and hitting `npm publish`.

> We are currently in an overhaul 🛠 👊🏼 of our docs

Glad to hear it, it's okay but I'm finding reading the code to be the most revealing thing right now. I was going to document a lot of what I'd had to figure out the hard way, I'll take a look at probot/friction tomorrow, I know I'm not really very in-love with plugin loading right now. But I've circumvented the `probot run` command in favour of programatic access to make loading a bit more automatic.

**Comment by bkeepers** [comment]
Hey @BlueHatbRit, I just pushed 1.1.0.

> I know I'm not really very in-love with plugin loading right now. But I've circumvented the `probot run` command in favour of programatic access to make loading a bit more automatic.

More feedback here would definitely be appreciated.

**Comment by BlueHatbRit** [comment]
@bkeepers cheers for that, I'm trying to figure out what's causing the friction. I'm going to be doing some probot work this weekend so hopefully I'll have some coherent feedback to post on probot/friction soon.

**Comment by bkeepers** [comment]
Sounds good.

Is your code public? Feel free to ping me on any PRs or issues related to what you're working on. I'd love to see it just to better understand the use case.
