### ISSUE TITLE
Change default stale label

### ISSUE THREAD

**Issue by waldyrious** [probot/stale#74]
"wontfix" does not accurately reflect the appropriate (candidate!) resolution for a stale issue, most of the time, and in fact can be very unfriendly when used incorrectly in such cases. Perhaps "waiting" or "on hold" would work better as default labels.

See [here](https://github.com/benbalter/licensee/issues/114#issuecomment-292254460) for an example of such a negative interaction that could have been avoided by better wording.

**Comment by bkeepers** [comment]
Hey @waldyrious, thanks for the suggestion. While I totally understand the negative connotations with `wontfix`, it is the default for a couple reasons:

1. It already exists by default on every repository
2. It quite literally means that the maintainers "will not fix" or do not intend to fix this issue for whatever reason

I'm not opposed to changing it if a lot of people feel it's not the right label. I think the bigger issue is actually the wording of the default message, which is being discussed in #67.

**Comment by waldyrious** [comment]
> It quite literally means that the maintainers "will not fix"

That's part of the issue: while a thorough reading indeed suggests that the intended meaning is "this issue will not be fixed *unless further action occurs*", the first impact is that of an immediate rejection without prior notice. I think you'd agree that this is not a good default experience.

> It already exists by default on every repository

It's my understanding that the "good first issue" label has recently been promoted to such a default status (see https://github.com/MunGell/awesome-for-beginners/pull/154, https://github.com/MunGell/awesome-for-beginners/pull/151). I don't see why "waiting" or "on hold", which IIUC are as common, if not more, couldn't be handled the same way, for the same reasons. (I do understand that this repository is not the place to request that change, though.)

> I think the bigger issue is actually the wording of the default message, which is being discussed in #67.

I fully agree. I've added a comment on that issue with our experience with the bot in the tldr-pages project.

**Comment by waldyrious** [comment]
It is still relevant. Perhaps @bkeepers could comment on what, if anything, is holding up progress?

**Comment by bkeepers** [comment]
> It is still relevant. Perhaps @bkeepers could comment on what, if anything, is holding up progress?

To quote my previous reply:

> I'm not opposed to changing it if a lot of people feel it's not the right label. I think the bigger issue is actually the wording of the default message, which is being discussed in #67.

Personally I feel like `wontfix` is the right default. If others disagree, then please explain why here.

**Comment by waldyrious** [comment]
> Personally I feel like `wontfix` is the right default. If others disagree, then please explain why here.

I disagree for the reasons I mentioned above (emphasised/edited for clarity):

> while [...] the intended meaning is "this issue will not be fixed unless further action occurs", **the first impact [of the addition of a label named "wontfix"] is that of an immediate rejection without prior notice.** I think you'd agree that this is not a good default experience.

That said, I won't insist further if nobody else cares.

**Comment by waldyrious** [comment]
(Just to reinforce what's actionable here: the alternative to "wontfix" proposed in this issue is "waiting", "on hold", or something along those lines.)

**Comment by christianbundy** [comment]
I'd like to support this change from "wontfix" to "stale". Personally, it comes down to the common understanding of what WONTFIX means in many/most projects:

> https://bugzilla.suse.com/page.cgi?id=fields.html#resolution
>
> explains WONTFIX only in very short terms:
> 
> "WONTFIX The problem described is a bug which will never be fixed."
>
>That means that WONTFIX acknowledges that a bug as reported is indeed a valid bug. But it also says that it will not be fixed: Not in the near future (that would be status ACCEPTED), not in some future release (that would be LATER), never.
>
>It means that whoever is responsible for the piece of software against which the bug was reported has examined the situation and evaluated possible approaches to fix the problem. But the conclusion of that process was that the bug will not be fixed.
>
>Of course, this is unsatisfactory for a user who took the trouble to make a bug report. Agreed. But there are also other considerations to take into account.
> 
> -- https://en.opensuse.org/Bug_Status_WONTFIX

In my experience, a WONTFIX should always come with a [human] description of why a ticket will *never* be resolved. It's the equivalent of saying "no", and is *personally* I'd prefer to just use "stale" rather than overload the semantics behind the WONTFIX label. I love being able to sort by `label:stale` and know that these are all stale, wherease `label:wontfix` brings up all sorts of tickets that actually conform to my definition of WONTFIX.

Anyway, just my two cents.

**Comment by waldyrious** [comment]
#109 fixes this -- please merge or close.

**Comment by waldyrious** [comment]
I've created #252 to address this.

**Comment by christianbundy** [comment]
this is fun, I'm having fun

**Comment by christianbundy** [comment]
> Is this still relevant?

Absolutely.

>  If so, what is blocking it?

Lack of maintainers.

>Is there anything you can do to help move it forward?

I guess I could fork but I'd really rather not.

**Comment by christianbundy** [comment]
** **

**Comment by waldyrious** [comment]
bump

**Comment by n-in0** [comment]
Can someone write a bot to send a message on this issue every times the label is set to `wontfix`?

**Comment by andig** [comment]
bump due to #294. In would be really nice if maintainers could act instead of bot asking the same question over and over :(

**Comment by JamesMGreene** [comment]
I left an alternative suggestion for resolution of #294 in that issue.

**Comment by christianbundy** [comment]
this would be funny if it wasn't so disappointing

**Comment by JamesMGreene** [comment]
Apologies to all of you who have expressed interest in this change but, alas, we are going to close it as `wontfix` (and yes, I absolutely see the irony) based on the discussion included in https://github.com/probot/stale/pull/252 (namely, the unavoidable negative impact to existing installations).

I fully empathize with you all on this one. 💔  I agree that `stale` is a more practical default value to use but based on the historical configuration and large installation count, I also concur that it is best not to change that now. 😕  

Also, my apologies that we did not close this sooner. 🙇🏻‍♂️

**Comment by andig** [comment]
@JamesMGreene afaiks the stale labek is not configrable. Why not just make that and keep wontfix as default?

**Comment by waldyrious** [comment]
Although the outcome wasn't what I desired, I appreciate your taking the time to close the issue and explain the rationale (and express your support), @JamesMGreene. 💔 indeed.

**Comment by christianbundy** [comment]
@andig It's configurable, this issue is only about changing the default.
