### ISSUE TITLE
Feature request: add an option to disable closing down stale issues/PRs

### ISSUE THREAD

**Issue by taketwo** [probot/stale#79]
In our project we would like to leave stale PRs open even if they do not receive any activity. As there is no documentation regarding how to achieve this, we naively tried to comment out

```yaml
# daysUntilClose: 7
```

Apparently, this does not help as the default value of 7 is picked up.

Would be helpful if it was possible to write something like `daysUntilClose: false` or perhaps a separate option `closeStale: false`.

**Comment by bkeepers** [comment]
Good suggestion. PRs are welcome. In the mean time, you can just set it to an insanely high number (e.g. 9125 days is 25 years from now, and I sure hope I'm retired by then and it's someone else's problem).

**Comment by tcbyrd** [comment]
@taketwo I'm going to take a crack at a PR for this, but in the meantime can you set your `daysUntilClose` to 10000 instead of [100 years](https://github.com/PointCloudLibrary/pcl/pull/2166)? Since 100 years ago is before 1970, it's raising some errors on the server.

**Comment by taketwo** [comment]
Thanks in advance. I've pushed a change to 10000.
