### ISSUE TITLE
Request: Labels configuration

### ISSUE THREAD

**Issue by jahirfiquitiva** [probot/stale#87]
Hello

Firsrt of all, thanks for this awesome app

I wanted to ask you, if possible, to add a feature to create configs for a specific label.

For example, if I add the lable `invalid` to an issue/PR, I would like it to be marked as stale after 1 single day and get closed after 2 days. But for any other issue with any other label, I would like it to be marked as stale after 4 days and get closed after 7 days

I am not sure if this is already available but it would be awesome to have.

Thanks in advance :)

**Comment by humitos** [comment]
Seems to be duplicated of #65

**Comment by bkeepers** [comment]
Closing as duplicate
