### ISSUE TITLE
Open PR with default config after installing the integration

### ISSUE THREAD

**Issue by bkeepers** [probot/stale#9]

**Comment by MikeMcQuaid** [comment]
If you explicitly add probot-stale to a specific repository (rather than globally on an organisation): this could be something done by default after addition? No idea whether you can easily identify that, though.

**Comment by bkeepers** [comment]
Good idea.  There's a `repository_selection` in the [webhook](https://developer.github.com/v3/activity/events/types/#installationevent) that can be used to determine this, and an [`installation_repositories`](https://developer.github.com/v3/activity/events/types/#installationrepositoriesevent) event when repositories are added later.

**Comment by aryannarora** [comment]
@bkeepers Can i work on this issue?

**Comment by TK101518** [comment]
Download
