### ISSUE TITLE
Stale bot is using label "wontfix" even though a different label is configured

### ISSUE THREAD

**Issue by mezz** [probot/stale#95]
Example of the bot applying and removing the "wontfix" label:
https://github.com/MinecraftForge/MinecraftForge/pull/4673#issuecomment-364836718

`stale.yml` config file:
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/.github/stale.yml

I expect it to be using the "Stale" label, it has been until just recently.

**Comment by bkeepers** [comment]
Sorry about that. Fix deploying now.

**Comment by mezz** [comment]
Thanks!
