### ISSUE TITLE
Stale not working

### ISSUE THREAD

**Issue by jahirfiquitiva** [probot/stale#97]
Hello and thanks for this awesome app

I wanted to report that Stale isn't working in any of my projects. There's [Blueprint](https://github.com/jahirfiquitiva/Blueprint), for example, where there are a couple issues that are 3 days old but stale bot haesn't done anything to them.

Is there something wrong in the configuration `stale.yml` file?
Thanks in advance. 🙂

**Comment by smit9612** [comment]
did you made it working?
